### PR TITLE
adding blocking and non-blocking rtsp stream

### PR DESCRIPTION
**Pull request by Benehiko**
This might fix the stream errors in issue #25
Also refactored the code a bit since we do not want to display a window from within the API (offload to the person implementing it).

### CODE REVIEW

**Comment by themoosman** [comment]
I did some testing this afternoon but wasn't able to get anything working.

**Comment by Benehiko** [comment]
> I did some testing this afternoon but wasn't able to get anything working.

What were the errors you got ?

**Comment by themoosman** [comment]
When running the streaming_video.py example using 'blocking()' I see.
```
[kmoos reolink-python-api]$ python3 examples/streaming_video.py 
Login success
Error connecting to SOCKS5 proxy 127.0.0.1:8000: [Errno 111] Connection refused
Error connecting to SOCKS5 proxy 127.0.0.1:8000: [Errno 111] Connection refused
Gtk-Message: 16:51:18.529: Failed to load module "pk-gtk-module"
'NoneType' object has no attribute 'send'
Traceback (most recent call last):
  File "/home/kmoos/.local/lib/python3.9/site-packages/api/recording.py", line 44, in open_video_stream
    rtsp_client.preview()
  File "/home/kmoos/.local/lib/python3.9/site-packages/RtspClient.py", line 78, in preview
    cv2.imshow(win_name, self.get_frame())
cv2.error: OpenCV(4.5.0) /home/kmoos/opencv/modules/highgui/src/window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kmoos/git/reolink-python-api/examples/streaming_video.py", line 82, in <module>
    blocking()
  File "/home/kmoos/git/reolink-python-api/examples/streaming_video.py", line 33, in blocking
    stream = c.open_video_stream()
  File "/home/kmoos/.local/lib/python3.9/site-packages/api/recording.py", line 44, in open_video_stream
    rtsp_client.preview()
  File "/home/kmoos/.local/lib/python3.9/site-packages/RtspClient.py", line 34, in __exit__
    self.sockt.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by Benehiko** [comment]
Did you checkout from dev branch? This seems like the old SOCKS error which was fixed up in commit cf540d1a95a9509ae4d21157eb3f8ea8e127f1fb

**Comment by themoosman** [comment]
Okay, so I got `blocking()` to work (my issue).  Now `nonblocking()` returns:

```
[kmoos reolink-python-api]$ python3 streaming_video.py 
calling non-blocking
Login success
opening stream
Traceback (most recent call last):
  File "/home/kmoos/git/reolink-python-api/streaming_video.py", line 81, in <module>
    non_blocking()
  File "/home/kmoos/git/reolink-python-api/streaming_video.py", line 21, in non_blocking
    print(t.isAlive())
AttributeError: 'Thread' object has no attribute 'isAlive'
```

**Comment by Benehiko** [comment]
image

might be an issue with python deprecating the camel case isAlive(). On my side it looks and works fine (running Python 3.6.7).
https://docs.python.org/3/library/threading.html#threading.Thread.is_alive

change the call to snake case and see if that works?

**Comment by themoosman** [comment]
@Benehiko I tested `is_alive()` and it worked just fine.  The PR has been updated with the new call.
Did you want to test again on Python 3.6?  Python 3.6 is kind of old.

**Review by themoosman — APPROVED** [review]
LGTM

**Comment by Benehiko** [comment]
> @Benehiko I tested `is_alive()` and it worked just fine. The PR has been updated with the new call.
> Did you want to test again on Python 3.6? Python 3.6 is kind of old.

Awesome! Yeah we can upgrade to a newer supported version such as Python 3.8?
Will merge and update pypi to v0.0.5

**Pull request merged**
